# Generated by Django 4.0.1 on 2022-01-28 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_alter_exam_detail_examiner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option1', models.CharField(max_length=15)),
                ('option2', models.CharField(max_length=15)),
                ('option3', models.CharField(max_length=15)),
                ('option4', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='mcq',
            name='option1',
        ),
        migrations.RemoveField(
            model_name='mcq',
            name='option2',
        ),
        migrations.RemoveField(
            model_name='mcq',
            name='option3',
        ),
        migrations.RemoveField(
            model_name='mcq',
            name='option4',
        ),
        migrations.AddField(
            model_name='mcq',
            name='option',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exam.option'),
            preserve_default=False,
        ),
    ]
